apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u97fihv4n-nodejs
  janus-idp.io/tekton: u97fihv4n-nodejs
  backstage.io/kubernetes-id: u97fihv4n-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u97fihv4n-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
